<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class EmployeeTest extends TestCase
{
    use RefreshDatabase;

    private $user;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user=User::create([

        ]);
    }

    /**
     * A basic feature test example.
     */


    public function test_index_exsists(): void
    {
        $response = $this->get(route("employees.index"));

        $response->assertStatus(200);
    }

    public function test_create_exsists(): void
    {
        $response = $this->get(route("employees.create"));

        $response->assertStatus(200);
    }

    public function test_store_employee(): void
    {

        $this->post(route("employees.store"),[
            'name'=>"ADSasf",
            "surname"=>"surnaem"
        ])->assertStatus(302);
    }
}
